description:
  Sent by a controller when a new configuration is available.
type: object
properties:
  method:
    description:
      A String containing the name of the method to be invoked.
    type: string
    const: configure
  params:
    type: object
    properties:
      uuid:
        description:
          The unique ID of the configuration. This is the unix timestamp of
          when the config was created.
        type: integer
    required: [ uuid ]
    additionalProperties: true
required: [ method, params ]
